apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: nginx
    version: v1.0
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
      name: http
