version: '3.8'

services:
  web:
    image: stackdemo
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
    networks:
      - webnet
    depends_on:
      - redis

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
