version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    deploy:
      replicas: 3
    networks:
      - webnet

  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: password123
    deploy:
      replicas: 1
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
