apiVersion: v1
kind: Pod
metadata:
  name: postgres-database
  labels:
    app: database
    tier: backend
spec:
  containers:
  - name: postgres
    image: postgres:13
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "myapp"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "password123"
