# Simple API Service for Todo App
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: todo-app
data:
  server.js: |
    const express = require('express');
    const { Pool } = require('pg');
    const cors = require('cors');
    
    const app = express();
    const port = 3000;
    
    // Middleware
    app.use(cors());
    app.use(express.json());
    
    // Database connection
    const pool = new Pool({
      host: 'postgresql-service',
      port: 5432,
      database: 'todoapp',
      user: 'postgres',
      password: 'todoapp123'
    });
    
    // Initialize database
    async function initDB() {
      try {
        await pool.query(`
          CREATE TABLE IF NOT EXISTS todos (
            id SERIAL PRIMARY KEY,
            text TEXT NOT NULL,
            completed BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          )
        `);
        console.log('Database initialized');
      } catch (err) {
        console.error('Database init error:', err);
      }
    }
    
    // Routes
    app.get('/health', (req, res) => {
      res.json({ status: 'healthy', service: 'todo-api' });
    });
    
    // Get all todos
    app.get('/todos', async (req, res) => {
      try {
        const result = await pool.query('SELECT * FROM todos ORDER BY created_at DESC');
        res.json(result.rows);
      } catch (err) {
        console.error(err);
        res.status(500).json({ error: 'Database error' });
      }
    });
    
    // Add new todo
    app.post('/todos', async (req, res) => {
      try {
        const { text } = req.body;
        const result = await pool.query(
          'INSERT INTO todos (text) VALUES ($1) RETURNING *',
          [text]
        );
        res.json(result.rows[0]);
      } catch (err) {
        console.error(err);
        res.status(500).json({ error: 'Database error' });
      }
    });
    
    // Delete todo
    app.delete('/todos/:id', async (req, res) => {
      try {
        const { id } = req.params;
        await pool.query('DELETE FROM todos WHERE id = $1', [id]);
        res.json({ message: 'Todo deleted' });
      } catch (err) {
        console.error(err);
        res.status(500).json({ error: 'Database error' });
      }
    });
    
    // Start server
    app.listen(port, () => {
      console.log(`Todo API running on port ${port}`);
      initDB();
    });
  
  package.json: |
    {
      "name": "todo-api",
      "version": "1.0.0",
      "main": "server.js",
      "dependencies": {
        "express": "^4.18.0",
        "pg": "^8.8.0",
        "cors": "^2.8.5"
      },
      "scripts": {
        "start": "node server.js"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: node:16-alpine
        ports:
        - containerPort: 3000
        workingDir: /app
        command: ["/bin/sh"]
        args: ["-c", "npm install && npm start"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: app-code
        configMap:
          name: api-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: todo-app
spec:
  selector:
    app: api-service
  ports:
  - port: 3000
    targetPort: 3000
