services:
  # Simple Flask app with DataDog metrics
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DD_API_KEY=demo-key-12345
      - DD_APP_KEY=demo-app-67890
    container_name: datadog-demo-app

  # Prometheus for comparison
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus-demo

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    container_name: grafana-demo
