apiVersion: apps/v1              # Kubernetes API version
kind: Deployment                 # Resource type
metadata:
  name: my-app                   # Deployment name
  labels:                        # Labels for the deployment
    app: my-app
    version: v1.0
  annotations:                   # Additional metadata
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 3                    # Desired number of pods
  selector:                      # Pod selector
    matchLabels:
      app: my-app
  strategy:                      # Update strategy
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:                      # Pod template
    metadata:
      labels:                    # Pod labels
        app: my-app
        version: v1.0
    spec:
      containers:
      - name: web                # Container name
        image: nginx:1.21        # Container image
        ports:
        - containerPort: 80      # Container port
        resources:               # Resource limits
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:           # Health checks
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
