# Development App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  namespace: development
  labels:
    app: dev-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: app
        image: nginx:1.21
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
# Staging App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-app
  namespace: staging
  labels:
    app: staging-app
    environment: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: staging-app
  template:
    metadata:
      labels:
        app: staging-app
    spec:
      containers:
      - name: app
        image: nginx:1.21
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
---
# Production App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
  namespace: production
  labels:
    app: prod-app
    environment: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: app
        image: nginx:1.21
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
# Team Alpha App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-app
  namespace: team-alpha
  labels:
    app: alpha-app
    team: alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpha-app
  template:
    metadata:
      labels:
        app: alpha-app
    spec:
      containers:
      - name: app
        image: httpd:2.4
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
---
# Team Beta App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-app
  namespace: team-beta
  labels:
    app: beta-app
    team: beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta-app
  template:
    metadata:
      labels:
        app: beta-app
    spec:
      containers:
      - name: app
        image: httpd:2.4
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
