apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    environment: development
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
