apiVersion: v1
kind: Pod
metadata:
  name: blue-app
  labels:
    application: web-app
    color: blue
    version: v1.0
spec:
  containers:
  - name: httpd
    image: varunmanik/httpd:blue
    ports:
    - containerPort: 80
    env:
    - name: VERSION
      value: "Blue-v1.0"
