apiVersion: v1
kind: Pod
metadata:
  name: green-app
  labels:
    application: web-app
    color: green
    version: v2.0
spec:
  containers:
  - name: httpd
    image: varunmanik/httpd:green
    ports:
    - containerPort: 80
    env:
    - name: VERSION
      value: "Green-v2.0"
