apiVersion: v1
kind: Pod
metadata:
  name: frontend-1
  labels:
    app: web
    tier: frontend
    instance: "1"
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-2
  labels:
    app: web
    tier: frontend
    instance: "2"
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-3
  labels:
    app: web
    tier: frontend
    instance: "3"
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: web
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
