# Database Service and Deployment
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    tier: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: ecommerce
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password123
        ports:
        - containerPort: 5432
