# Simple multi-tenant setup - no complex RBAC
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    tier: frontend
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    tier: backend
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    tier: database
    environment: development
---
# Simple frontend app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
# Simple backend app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
