# Test pods for service examples
---
# Blue app pod
apiVersion: v1
kind: Pod
metadata:
  name: blue-app
  labels:
    application: web-app
    color: blue
    app: web
    version: blue
spec:
  containers:
  - name: httpd
    image: varunmanik/httpd:blue
    ports:
    - containerPort: 80
---
# Green app pod
apiVersion: v1
kind: Pod
metadata:
  name: green-app
  labels:
    application: web-app
    color: green
    app: web
    version: green
spec:
  containers:
  - name: httpd
    image: varunmanik/httpd:green
    ports:
    - containerPort: 80
---
# Web pod for ClusterIP testing
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
