# Pod with labels for organization
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    environment: development
spec:
  containers:
  - name: myapp
    image: varunmanik/httpd:green
    ports:
    - containerPort: 80
